### ISSUE TITLE
请问有没有能够用来订阅的 rss 源？

### ISSUE THREAD

**Issue by choleraehyq** [SF-Zhou/sf-zhou.github.io#108]

**Comment by SF-Zhou** [comment]
谢谢支持，没有支持 RSS。最近应该会开个微信公众号同步博客内容，等申请好了这里放二维码哈。

**Comment by SF-Zhou** [comment]
欢迎关注订阅号 `SF Zhou`
<img src="https://user-images.githubusercontent.com/7477599/88472840-c7cec300-cf49-11ea-8b85-8dcebfe2adc8.png" width="172">

**Comment by choleraehyq** [comment]
@SF-Zhou 赞，过往文章还有计划同步过来吗

**Comment by SF-Zhou** [comment]
> @SF-Zhou 赞，过往文章还有计划同步过来吗

不会，公众号的编辑器限制太多，感觉没有必要。
