### ISSUE TITLE
朴素贝叶斯分类的 Python 实现和思考

### ISSUE THREAD

**Issue by SF-Zhou** [SF-Zhou/sf-zhou.github.io#13]
https://sf-zhou.github.io/algorithm/naive-bayes-python.html

**Comment by SF-Zhou** [comment]
本科做的毕业设计是继续这个做的，做了一个简单的综合几种特征选择方法的方法，来选特征。现在回过头来看，还是太稚嫩 :joy:

**Comment by itssyuu** [comment]
您好 请问一下这里的f指什么呀

# 我们使用二项独立模型，即仅统计一个单词有没有出现
    trainData.append((dict(map(lambda (i，f)：(names[i]，f > 0)，enumerate(x)))，c))
