### ISSUE TITLE
[Paper Summary] Convolutional Networks with Adaptive Inference Graphs | SF-Zhou 的博客

### ISSUE THREAD

**Issue by SF-Zhou** [SF-Zhou/sf-zhou.github.io#48]
https://sf-zhou.github.io/ml/adaptive_graphs.html

**Comment by SF-Zhou** [comment]
论文作者开源了自己的代码，见 [https://github.com/andreasveit/convnet-aig](https://github.com/andreasveit/convnet-aig)

**Comment by TLMichael** [comment]
写得很好！
