### ISSUE TITLE
Source Code Reading of LevelDB | SF-Zhou's Blog

### ISSUE THREAD

**Issue by SF-Zhou** [SF-Zhou/sf-zhou.github.io#51]
https://sf-zhou.github.io/programming/source_code_reading_of_leveldb.html

**Comment by IceHe** [comment]
瞅瞅

**Comment by SF-Zhou** [comment]
> @IceHe
> 瞅瞅

然而流水账一般……

**Comment by biuding** [comment]
手动赞楼主～！我也在读

**Comment by ck89119** [comment]
赞~

**Comment by SF-Zhou** [comment]
> @ck89119
> 赞~

英文表达不太行，后面整理了中文版，参见 https://sf-zhou.github.io/#/LevelDB
