### ISSUE TITLE
2017 互联网暑期实习应聘小结

### ISSUE THREAD

**Issue by SF-Zhou** [SF-Zhou/sf-zhou.github.io#6]
https://sf-zhou.github.io/life/2017_internship_interview.htm

**Comment by SF-Zhou** [comment]
其实没啥要填坑的了，实习结束了哈哈。Offer 等待中，可能有 :joy:

**Comment by SF-Zhou** [comment]
现在再回过头来看这篇小结，感慨万千。

**Comment by Expost** [comment]
> @SF-Zhou
> 现在再回过头来看这篇小结，感慨万千。
老哥最后去了微软吗？

**Comment by SF-Zhou** [comment]
> @Expost
> > @SF-Zhou
> > 现在再回过头来看这篇小结，感慨万千。
> 老哥最后去了微软吗？
> 

没有

**Comment by Expost** [comment]
> @SF-Zhou
> > @Expost
> > > @SF-Zhou
> > > 现在再回过头来看这篇小结，感慨万千。
> > 老哥最后去了微软吗？
> > 
> 
> 没有

😨那真是太遗憾了，果然想进微软还是很难的啊。

**Comment by renyajie** [comment]
博主你好，我也收到了苏州微软的实习，请问微软转正率高吗

**Comment by SF-Zhou** [comment]
> @renyajie
> 博主你好，我也收到了苏州微软的实习，请问微软转正率高吗

挺高，愿意留的一般都能留下来，即使第一批没有后面也有很多补录的机会

**Comment by renyajie** [comment]
谢谢博主



---原始邮件---
发件人: "SF-Zhou"<notifications@github.com&gt;
发送时间: 2020年5月12日(周二) 中午11:43
收件人: "SF-Zhou/sf-zhou.github.io"<sf-zhou.github.io@noreply.github.com&gt;;
抄送: "Thor"<renyj@bupt.edu.cn&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [SF-Zhou/sf-zhou.github.io] 2017 互联网暑期实习应聘小结 (#6)




  
@renyajie
 博主你好，我也收到了苏州微软的实习，请问微软转正率高吗
  
挺高，愿意留的一般都能留下来，即使第一批没有后面也有很多补录的机会
